### ISSUE TITLE
Kadane’s Algorithm : Maximum Subarray Sum in an Array in c++

### ISSUE THREAD

**Issue by SonaVarshney** [iamehran/hacktoberfest2022#34]
@iamehran I want to provide solution for 'Maximum sum subarray in array' using 'Kadane'algorithm' in C++ as it is the most efficient method. Please assign me this issue.

**Comment by SonaVarshney** [comment]
> @iamehran I want to provide solution for 'Maximum sum subarray in array' using 'Kadane'algorithm' in C++ as it is the most efficient method. Please assign me this issue.

https://github.com/iamehran/hacktoberfest2022/pull/35#issue-1403240414

**Comment by SonaVarshney** [comment]
#35 https://github.com/iamehran/hacktoberfest2022/pull/35#issue-1403240414

**Comment by iamehran** [comment]
Done.
