### ISSUE TITLE
Add live weather web page

### ISSUE THREAD

**Issue by AbhishekKumar2002** [iamehran/hacktoberfest2022#81]
Hi @iamehran, I want to add live weather information web page which will tell you about the weather information about the place you search. Please assign me this project under Hacktoberfest.

**Comment by iamehran** [comment]
you can add your project in Web dev folder.

**Comment by AbhishekKumar2002** [comment]
Please assign it to me under Hacktoberfest label @iamehran.

**Comment by AbhishekKumar2002** [comment]
Hi @iamehran I have added live weather web page. Please accept my PR.
