### ISSUE TITLE
add navigation links to shop and about in the footer sections

### ISSUE THREAD

**Issue by Akshitha2106** [iamehran/hacktoberfest2022#84]
![2022-10-18](https://user-images.githubusercontent.com/101176297/196397155-0c69808a-4cec-487a-b3a4-eb5a40b1f19c.png)
Respected sir (@iamehran ) please assign me this issue under hacktoberfest .

**Comment by mohitpal88** [comment]
can i do this plz assign me

**Comment by Akshitha2106** [comment]
respected sir pls assign me this under hacktoberfest.
