### ISSUE TITLE
Spiral print an array in C++

### ISSUE THREAD

**Issue by SonaVarshney** [iamehran/hacktoberfest2022#97]
Want to add Spiral printing an array in C++ folder, please assign me this issue

**Comment by m-mishra2001** [comment]
please assign me this task @iamehran

**Comment by SonaVarshney** [comment]
https://github.com/iamehran/hacktoberfest2022/pull/106#issue-1417994969 @iamehran , pls have a look

**Comment by iamehran** [comment]
done
